language: groovy
install:
- TERM=dumb ./gradlew -q assemble
script:
- TERM=dumb ./gradlew check
jdk:
- oraclejdk7
env:
  global:
  - secure: n7bZWaU2d1m1bpMQhz4XymWLljK0cGNo5/lqgx/1pB3xo2Q7gaRAQYf1UTjPYnl/zyxMbmxIKADCEIdE0BbbeFPw9pBNgk724JhSaMX9Ru+jaKAfvSrxddSWzN8YqqWGUg7E0gtrqRp+muzLqx4jvn7h79vVO0Pi4mjNVu+hw9w=
  - secure: rCZZWCW/OxvjBd0JEuav0oCIdlVP+8tHpxvGkE+7Nh2riSL20YkJEllC1BBrNyLccpd2WJJ1I1IbwB21w+yDFkgCIEmHveGLLeLFq5wjVdF7kyHlyHcymnUo6xUcombaXjWBXgLkw1aCK0FbW6jRiYB28nBD0g5JhwmX5aXo0PE=
